replicaCount: 3

service:
  type: ClusterIP

image:
  tag: "1.0.0"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  LOG_LEVEL: "warn"
